### ISSUE TITLE
Hide BottomSheet when tapping in the background

### ISSUE THREAD

**Issue by stesvis** [enzomanuelmangano/what-about-gestures#2]
Hello, first of all awesome tutorial on the BottomSheet!

I have a question, how can you hide it again if you tap outside of it, in the page background? Thanks!

**Comment by enzomanuelmangano** [comment]
Hi @stesvis I'm sorry for the huge delay. Basically tomorrow I'll upload talking about that :) 

[Creating a BottomSheet Backdrop in React Native](https://youtu.be/hfsBArfvK74)
